### ISSUE TITLE
Current ldap_connect format is deprecated in PHP 8.3

### ISSUE THREAD

**Issue by kswan** [backdrop-contrib/ldap#12]
While investigating a problem I have when an LDAP server is not responding, I noticed an issue that occur when sites move to PHP 8.3.

According to, https://www.php.net/manual/en/function.ldap-connect.php:
![image](https://github.com/backdrop-contrib/ldap/assets/154391/62762424-836f-445d-94df-9c51f50e610d)

https://github.com/backdrop-contrib/ldap/blob/0b301f8aef38ba0e556cf2d89e6b0e5f057e4748/ldap_servers/LdapServer.class.php#L346
uses the deprecated format.

**Comment by VasasA** [comment]
Thank you. I can test this solution next week:
```php
$ldapuri = $this->address . ':' . $this->port;
if (!$con = ldap_connect($ldapuri)) {
      watchdog('ldap_servers', 'LDAP Connect failure to ' . $ldapuri);
      return LDAP_CONNECT_ERROR;
    }
```

**Comment by kswan** [comment]
I believe a protocol is necessary.  So something like:

`$ldapuri = (($this->tls) ? "ldaps://" : "ldap://") . $this->address . ':' . $this->port;`

**Comment by VasasA** [comment]
@kswan Please consider the server's configuration page, the description of "LDAP server" input field: `The domain name or IP address of your LDAP Server such as "ad.unm.edu". For SSL use the form ldaps://DOMAIN such as "ldaps://ad.unm.edu"`

So:
```php
    $ldapuri = $this->address . ':' . $this->port;
    $ldapuri = strpos($this->address, 'ldaps://') === 0 ? $ldapuri : 'ldap://' . $ldapuri;
    if (!$con = ldap_connect($ldapuri)) {
      watchdog('ldap_servers', 'LDAP Connect failure to ' . $ldapuri);
      return LDAP_CONNECT_ERROR;
    }
```

**Comment by kswan** [comment]
@VasasA I don't have access to an ldaps server so I can't test it, but your code makes sense. 

Thank you.

**Comment by VasasA** [comment]
@kswan Thanks for the contribution. I published a new release.
